// Code generated by Slice Machine. DO NOT EDIT.

import BannerEvent from './BannerEvent/index.svelte';
import Hero from './Hero/index.svelte';
import RichText from './RichText/index.svelte';

export const components = {
	banner_event: BannerEvent,
	hero: Hero,
	rich_text: RichText
};
