// Code generated by Slice Machine. DO NOT EDIT.

import Evenements from './Evenements/index.svelte';
import Newsletter from './Newsletter/index.svelte';
import Avis from './Avis/index.svelte';
import Reseaux from './Reseaux/index.svelte';
import GalleryGrid from './GalleryGrid/index.svelte';
import Hero from './Hero/index.svelte';
import LocationContactInfo from './LocationContactInfo/index.svelte';
import NewsletterSignup from './NewsletterSignup/index.svelte';
import Produits from './Produits/index.svelte';
import Texte from './Texte/index.svelte';
import Espace from './Espace/index.svelte';
import Title from './Title/index.svelte';

export const components = {
	banner_event: Evenements,
	banner_newsletter: Newsletter,
	banner_review: Avis,
	banner_social: Reseaux,
	gallery_grid: GalleryGrid,
	hero: Hero,
	location_contact_info: LocationContactInfo,
	newsletter_signup: NewsletterSignup,
	produits: Produits,
	rich_text: Texte,
	spacer: Espace,
	title: Title
};
