// Code generated by Slice Machine. DO NOT EDIT.

import Evenements from './Evenements/index.svelte';
import Newsletter from './Newsletter/index.svelte';
import Avis from './Avis/index.svelte';
import Reseaux from './Reseaux/index.svelte';
import Hero from './Hero/index.svelte';
import Produits from './Produits/index.svelte';
import Texte from './Texte/index.svelte';
import Espace from './Espace/index.svelte';

export const components = {
	banner_event: Evenements,
	banner_newsletter: Newsletter,
	banner_review: Avis,
	banner_social: Reseaux,
	hero: Hero,
	produits: Produits,
	rich_text: Texte,
	spacer: Espace
};
