// Code generated by Slice Machine. DO NOT EDIT.

import BannerEvent from './BannerEvent/index.svelte';
import BannerNewsletter from './BannerNewsletter/index.svelte';
import BannerSocial from './BannerSocial/index.svelte';
import Hero from './Hero/index.svelte';
import RichText from './RichText/index.svelte';

export const components = {
	banner_event: BannerEvent,
	banner_newsletter: BannerNewsletter,
	banner_social: BannerSocial,
	hero: Hero,
	rich_text: RichText
};
