// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
	TRelationship extends
		| prismic.CustomTypeModelFetchCustomTypeLevel1
		| prismic.CustomTypeModelFetchCustomTypeLevel2
		| prismic.CustomTypeModelFetchGroupLevel1
		| prismic.CustomTypeModelFetchGroupLevel2,
	TData extends Record<
		string,
		prismic.AnyRegularField | prismic.GroupField | prismic.NestedGroupField | prismic.SliceZone
	>,
	TLang extends string
> =
	// Content relationship fields
	{
		[TSubRelationship in Extract<
			TRelationship['fields'][number],
			prismic.CustomTypeModelFetchContentRelationshipLevel1
		> as TSubRelationship['id']]: ContentRelationshipFieldWithData<
			TSubRelationship['customtypes'],
			TLang
		>;
	} & // Group
	{
		[TGroup in Extract<
			TRelationship['fields'][number],
			prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2
		> as TGroup['id']]: TData[TGroup['id']] extends prismic.GroupField<infer TGroupData>
			? prismic.GroupField<PickContentRelationshipFieldData<TGroup, TGroupData, TLang>>
			: never;
	} & // Other fields
	{
		[TFieldKey in Extract<TRelationship['fields'][number], string>]: TFieldKey extends keyof TData
			? TData[TFieldKey]
			: never;
	};

type ContentRelationshipFieldWithData<
	TCustomType extends
		| readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
		| readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
	TLang extends string = string
> = {
	[ID in Exclude<TCustomType[number], string>['id']]: prismic.ContentRelationshipField<
		ID,
		TLang,
		PickContentRelationshipFieldData<
			Extract<TCustomType[number], { id: ID }>,
			Extract<prismic.Content.AllDocumentTypes, { type: ID }>['data'],
			TLang
		>
	>;
}[Exclude<TCustomType[number], string>['id']];

/**
 * Content for Appellation documents
 */
interface AppellationDocumentData {
	/**
	 * Appellation field in *Appellation*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: appellation.appellation
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	appellation: prismic.KeyTextField;

	/**
	 * Description field in *Appellation*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: appellation.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
}

/**
 * Appellation document from Prismic
 *
 * - **API ID**: `appellation`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AppellationDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<AppellationDocumentData>,
	'appellation',
	Lang
>;

/**
 * Content for Catégorie documents
 */
interface CategoriesDocumentData {
	/**
	 * Nom field in *Catégorie*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: categories.nom
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	nom: prismic.KeyTextField;

	/**
	 * Ordre Menu field in *Catégorie*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: categories.ordre_menu
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/number
	 */
	ordre_menu: prismic.NumberField;
}

/**
 * Catégorie document from Prismic
 *
 * - **API ID**: `categories`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CategoriesDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<CategoriesDocumentData>,
	'categories',
	Lang
>;

type CaveDocumentDataSlicesSlice = SpacerSlice | BannerEventSlice | RichTextSlice;

/**
 * Content for Cave documents
 */
interface CaveDocumentData {
	/**
	 * Title field in *Cave*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cave.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;

	/**
	 * Slice Zone field in *Cave*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cave.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<CaveDocumentDataSlicesSlice> /**
	 * Meta Title field in *Cave*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: cave.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Cave*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: cave.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Cave*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cave.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Cave document from Prismic
 *
 * - **API ID**: `cave`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CaveDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<CaveDocumentData>,
	'cave',
	Lang
>;

/**
 * Content for Couleur documents
 */
interface CouleurDocumentData {
	/**
	 * Couleur field in *Couleur*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: couleur.couleur
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	couleur: prismic.KeyTextField;

	/**
	 * Ordre Menu field in *Couleur*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: couleur.ordre_menu
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/number
	 */
	ordre_menu: prismic.NumberField;
}

/**
 * Couleur document from Prismic
 *
 * - **API ID**: `couleur`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CouleurDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<CouleurDocumentData>,
	'couleur',
	Lang
>;

/**
 * Content for Domaine documents
 */
interface DomaineDocumentData {
	/**
	 * Domaine field in *Domaine*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: domaine.domaine
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	domaine: prismic.KeyTextField;

	/**
	 * Description field in *Domaine*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: domaine.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
}

/**
 * Domaine document from Prismic
 *
 * - **API ID**: `domaine`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DomaineDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<DomaineDocumentData>,
	'domaine',
	Lang
>;

type EpicerieDocumentDataSlicesSlice = never;

/**
 * Content for Épicerie documents
 */
interface EpicerieDocumentData {
	/**
	 * Title field in *Épicerie*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: epicerie.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;

	/**
	 * Slice Zone field in *Épicerie*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: epicerie.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<EpicerieDocumentDataSlicesSlice> /**
	 * Meta Title field in *Épicerie*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: epicerie.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Épicerie*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: epicerie.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Épicerie*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: epicerie.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Épicerie document from Prismic
 *
 * - **API ID**: `epicerie`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EpicerieDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<EpicerieDocumentData>,
	'epicerie',
	Lang
>;

/**
 * Content for Origine documents
 */
interface OrigineDocumentData {
	/**
	 * Ordre Menu field in *Origine*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: origine.ordre_menu
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/number
	 */
	ordre_menu: prismic.NumberField;

	/**
	 * Nom field in *Origine*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: origine.nom
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	nom: prismic.KeyTextField;

	/**
	 * Description field in *Origine*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: origine.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
}

/**
 * Origine document from Prismic
 *
 * - **API ID**: `origine`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OrigineDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<OrigineDocumentData>,
	'origine',
	Lang
>;

type PageDocumentDataSlicesSlice =
	| GalleryGridSlice
	| LocationContactInfoSlice
	| NewsletterSignupSlice
	| SpacerSlice
	| ProduitsSlice
	| BannerReviewSlice
	| BannerSocialSlice
	| BannerEventSlice
	| HeroSlice
	| RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
	/**
	 * Title field in *Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;

	/**
	 * Slice Zone field in *Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
	 * Meta Title field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Un titre de page utilisé pour les réseaux sociaux et les moteurs de recherche
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Un bref résumé de la page
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<PageDocumentData>,
	'page',
	Lang
>;

/**
 * Content for Région documents
 */
interface RegionDocumentData {
	/**
	 * Ordre Menu field in *Région*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: region.ordre_menu
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/number
	 */
	ordre_menu: prismic.NumberField;

	/**
	 * Région field in *Région*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: region.region
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	region: prismic.KeyTextField;

	/**
	 * Description field in *Région*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: region.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
}

/**
 * Région document from Prismic
 *
 * - **API ID**: `region`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RegionDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<RegionDocumentData>,
	'region',
	Lang
>;

/**
 * Item in *Paramètres → Navigation*
 */
export interface SettingsDocumentDataNavigationItem {
	/**
	 * Link field in *Paramètres → Navigation*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.navigation[].link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Label field in *Paramètres → Navigation*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.navigation[].label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;

	/**
	 * External Link field in *Paramètres → Navigation*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: settings.navigation[].external_link
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	external_link: prismic.BooleanField;
}

/**
 * Item in *Paramètres → item*
 */
export interface SettingsDocumentDataItemItem {
	/**
	 * icone field in *Paramètres → item*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.item[].icone
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	icone: prismic.ImageField<never>;

	/**
	 * lien field in *Paramètres → item*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.item[].lien
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	lien: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

type SettingsDocumentDataSlices3Slice = never;

type SettingsDocumentDataSlices4Slice = NewsletterSignupSlice;

/**
 * Content for Paramètres documents
 */
interface SettingsDocumentData {
	/**
	 * Site Title field in *Paramètres*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.site_title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	site_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Paramètres*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.meta_description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * OG Image field in *Paramètres*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.og_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	og_image: prismic.ImageField<never>;

	/**
	 * Navigation field in *Paramètres*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.navigation[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	navigation: prismic.GroupField<Simplify<SettingsDocumentDataNavigationItem>> /**
	 * Logo Header field in *Paramètres*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.logo_header
	 * - **Tab**: Logos
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */;
	logo_header: prismic.ImageField<never>;

	/**
	 * Logo Footer field in *Paramètres*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.logo_footer
	 * - **Tab**: Logos
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	logo_footer: prismic.ImageField<never> /**
	 * E-mail field in *Paramètres*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.email
	 * - **Tab**: Contact
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */;
	email: prismic.KeyTextField;

	/**
	 * Téléphone field in *Paramètres*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.telephone
	 * - **Tab**: Contact
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	telephone: prismic.KeyTextField;

	/**
	 * Adresse field in *Paramètres*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.adresse
	 * - **Tab**: Contact
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	adresse: prismic.KeyTextField;

	/**
	 * GoogleMap field in *Paramètres*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.googlemap
	 * - **Tab**: Contact
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	googlemap: prismic.KeyTextField /**
	 * Texte field in *Paramètres*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.texte
	 * - **Tab**: Réseaux Sociaux
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */;
	texte: prismic.RichTextField;

	/**
	 * item field in *Paramètres*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.item[]
	 * - **Tab**: Réseaux Sociaux
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	item: prismic.GroupField<Simplify<SettingsDocumentDataItemItem>>;

	/**
	 * Slice Zone field in *Paramètres*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.slices3[]
	 * - **Tab**: Réseaux Sociaux
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices3: prismic.SliceZone<SettingsDocumentDataSlices3Slice> /**
	 * Slice Zone field in *Paramètres*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.slices4[]
	 * - **Tab**: Slices
	 * - **Documentation**: https://prismic.io/docs/slices
	 */;
	slices4: prismic.SliceZone<SettingsDocumentDataSlices4Slice>;
}

/**
 * Paramètres document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<SettingsDocumentData>,
	'settings',
	Lang
>;

type VinDocumentDataSlicesSlice = BannerSocialSlice | SpacerSlice | BannerEventSlice;

/**
 * Content for Vin documents
 */
interface VinDocumentData {
	/**
	 * Titre field in *Vin*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: vin.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;

	/**
	 * Image field in *Vin*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: vin.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Région field in *Vin*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: vin.region
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/content-relationship
	 */
	region: prismic.ContentRelationshipField<'region'>;

	/**
	 * Domaine field in *Vin*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: vin.domaine
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/content-relationship
	 */
	domaine: prismic.ContentRelationshipField<'domaine'>;

	/**
	 * Appellation field in *Vin*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: vin.appellation
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/content-relationship
	 */
	appellation: prismic.ContentRelationshipField<'appellation'>;

	/**
	 * Cépages field in *Vin*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: vin.cepages
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	cepages: prismic.KeyTextField;

	/**
	 * Dégustation field in *Vin*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Se déguste avec...
	 * - **API ID Path**: vin.degustation
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	degustation: prismic.RichTextField;

	/**
	 * Terroir field in *Vin*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: vin.terroir
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	terroir: prismic.KeyTextField;

	/**
	 * Couleur field in *Vin*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: vin.couleur
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/content-relationship
	 */
	couleur: prismic.ContentRelationshipField<'couleur'>;

	/**
	 * Prix field in *Vin*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: Sélectionner la fourchette de prix
	 * - **Default Value**: 5-10
	 * - **API ID Path**: vin.prix
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	prix: prismic.SelectField<'5-10' | '11-20' | '21-40' | '41-80' | '81-120' | '121', 'filled'>;

	/**
	 * À l'oeil field in *Vin*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: vin.oeil
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	oeil: prismic.KeyTextField;

	/**
	 * Au nez field in *Vin*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: vin.nez
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	nez: prismic.KeyTextField;

	/**
	 * En bouche field in *Vin*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: vin.bouche
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	bouche: prismic.KeyTextField;

	/**
	 * résumé field in *Vin*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: vin.resume
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	resume: prismic.RichTextField;

	/**
	 * Nouveauté field in *Vin*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: vin.nouveaute
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	nouveaute: prismic.BooleanField;

	/**
	 * Slice Zone field in *Vin*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: vin.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<VinDocumentDataSlicesSlice> /**
	 * Meta Title field in *Vin*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Un titre de page utilisé pour les réseaux sociaux et les moteurs de recherche
	 * - **API ID Path**: vin.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Vin*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Un bref résumé de la page
	 * - **API ID Path**: vin.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Vin*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: vin.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Vin document from Prismic
 *
 * - **API ID**: `vin`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type VinDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<VinDocumentData>,
	'vin',
	Lang
>;

export type AllDocumentTypes =
	| AppellationDocument
	| CategoriesDocument
	| CaveDocument
	| CouleurDocument
	| DomaineDocument
	| EpicerieDocument
	| OrigineDocument
	| PageDocument
	| RegionDocument
	| SettingsDocument
	| VinDocument;

/**
 * Primary content in *Evenements → Standard → Primary*
 */
export interface BannerEventSliceDefaultPrimary {
	/**
	 * Text field in *Evenements → Standard → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: banner_event.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	text: prismic.RichTextField;

	/**
	 * Link field in *Evenements → Standard → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: banner_event.default.primary.link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Label field in *Evenements → Standard → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: banner_event.default.primary.label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;
}

/**
 * Standard variation for Evenements Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BannerEventSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<BannerEventSliceDefaultPrimary>,
	never
>;

/**
 * Primary content in *Evenements → Large → Primary*
 */
export interface BannerEventSliceBannerEventXlPrimary {
	/**
	 * Text field in *Evenements → Large → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: banner_event.bannerEventXl.primary.text
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	text: prismic.RichTextField;

	/**
	 * Link field in *Evenements → Large → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: banner_event.bannerEventXl.primary.link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Label field in *Evenements → Large → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: banner_event.bannerEventXl.primary.label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;
}

/**
 * Large variation for Evenements Slice
 *
 * - **API ID**: `bannerEventXl`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BannerEventSliceBannerEventXl = prismic.SharedSliceVariation<
	'bannerEventXl',
	Simplify<BannerEventSliceBannerEventXlPrimary>,
	never
>;

/**
 * Slice variation for *Evenements*
 */
type BannerEventSliceVariation = BannerEventSliceDefault | BannerEventSliceBannerEventXl;

/**
 * Evenements Shared Slice
 *
 * - **API ID**: `banner_event`
 * - **Description**: BannerEvent
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BannerEventSlice = prismic.SharedSlice<'banner_event', BannerEventSliceVariation>;

/**
 * Primary content in *Avis → Default → Primary*
 */
export interface BannerReviewSliceDefaultPrimary {
	/**
	 * Title field in *Avis → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: banner_review.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;

	/**
	 * Link field in *Avis → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: banner_review.default.primary.link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Label field in *Avis → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: banner_review.default.primary.label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;
}

/**
 * Primary content in *Avis → Items*
 */
export interface BannerReviewSliceDefaultItem {
	/**
	 * Subtitle field in *Avis → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: banner_review.items[].subtitle
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	subtitle: prismic.RichTextField;

	/**
	 * Text field in *Avis → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: banner_review.items[].text
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	text: prismic.RichTextField;
}

/**
 * Default variation for Avis Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BannerReviewSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<BannerReviewSliceDefaultPrimary>,
	Simplify<BannerReviewSliceDefaultItem>
>;

/**
 * Slice variation for *Avis*
 */
type BannerReviewSliceVariation = BannerReviewSliceDefault;

/**
 * Avis Shared Slice
 *
 * - **API ID**: `banner_review`
 * - **Description**: BannerReview
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BannerReviewSlice = prismic.SharedSlice<'banner_review', BannerReviewSliceVariation>;

/**
 * Primary content in *Reseaux → Default → Primary*
 */
export interface BannerSocialSliceDefaultPrimary {
	/**
	 * Text field in *Reseaux → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: banner_social.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	text: prismic.RichTextField;
}

/**
 * Primary content in *Reseaux → Items*
 */
export interface BannerSocialSliceDefaultItem {
	/**
	 * Icon field in *Reseaux → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: banner_social.items[].icon
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	icon: prismic.ImageField<never>;

	/**
	 * Link field in *Reseaux → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: banner_social.items[].link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for Reseaux Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BannerSocialSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<BannerSocialSliceDefaultPrimary>,
	Simplify<BannerSocialSliceDefaultItem>
>;

/**
 * Slice variation for *Reseaux*
 */
type BannerSocialSliceVariation = BannerSocialSliceDefault;

/**
 * Reseaux Shared Slice
 *
 * - **API ID**: `banner_social`
 * - **Description**: BannerSocial
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BannerSocialSlice = prismic.SharedSlice<'banner_social', BannerSocialSliceVariation>;

/**
 * Item in *GalleryGrid → 3x2 Grid → Primary → Images*
 */
export interface GalleryGridSliceThreeByTwoGridPrimaryImagesItem {
	/**
	 * Image field in *GalleryGrid → 3x2 Grid → Primary → Images*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: gallery_grid.three_by_two_grid.primary.images[].image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Primary content in *GalleryGrid → 3x2 Grid → Primary*
 */
export interface GalleryGridSliceThreeByTwoGridPrimary {
	/**
	 * Images field in *GalleryGrid → 3x2 Grid → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: gallery_grid.three_by_two_grid.primary.images[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	images: prismic.GroupField<Simplify<GalleryGridSliceThreeByTwoGridPrimaryImagesItem>>;

	/**
	 * Show Captions field in *GalleryGrid → 3x2 Grid → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **API ID Path**: gallery_grid.three_by_two_grid.primary.show_captions
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	show_captions: prismic.BooleanField;

	/**
	 * Caption Text field in *GalleryGrid → 3x2 Grid → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: gallery_grid.three_by_two_grid.primary.caption_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	caption_text: prismic.KeyTextField;
}

/**
 * 3x2 Grid variation for GalleryGrid Slice
 *
 * - **API ID**: `three_by_two_grid`
 * - **Description**: Displays six images arranged evenly in two rows of three, typically for showcasing grouped sets or featured content in a gallery format.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GalleryGridSliceThreeByTwoGrid = prismic.SharedSliceVariation<
	'three_by_two_grid',
	Simplify<GalleryGridSliceThreeByTwoGridPrimary>,
	never
>;

/**
 * Slice variation for *GalleryGrid*
 */
type GalleryGridSliceVariation = GalleryGridSliceThreeByTwoGrid;

/**
 * GalleryGrid Shared Slice
 *
 * - **API ID**: `gallery_grid`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GalleryGridSlice = prismic.SharedSlice<'gallery_grid', GalleryGridSliceVariation>;

/**
 * Primary content in *Hero → HeroImage → Primary*
 */
export interface HeroSliceDefaultPrimary {
	/**
	 * Image field in *Hero → HeroImage → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Title field in *Hero → HeroImage → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;

	/**
	 * Text field in *Hero → HeroImage → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	text: prismic.RichTextField;

	/**
	 * Link field in *Hero → HeroImage → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Label field in *Hero → HeroImage → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;
}

/**
 * HeroImage variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HeroSliceDefaultPrimary>,
	never
>;

/**
 * Primary content in *Hero → HeroTexte → Primary*
 */
export interface HeroSliceHeroTextOnlyPrimary {
	/**
	 * Title field in *Hero → HeroTexte → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.heroTextOnly.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;

	/**
	 * Text field in *Hero → HeroTexte → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.heroTextOnly.primary.text
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	text: prismic.RichTextField;
}

/**
 * HeroTexte variation for Hero Slice
 *
 * - **API ID**: `heroTextOnly`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceHeroTextOnly = prismic.SharedSliceVariation<
	'heroTextOnly',
	Simplify<HeroSliceHeroTextOnlyPrimary>,
	never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceHeroTextOnly;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<'hero', HeroSliceVariation>;

/**
 * Item in *LocationContactInfo → Map, Address & Contact → Primary → Contact Methods*
 */
export interface LocationContactInfoSliceMapAddressContactPrimaryContactMethodsItem {
	/**
	 * Method Type field in *LocationContactInfo → Map, Address & Contact → Primary → Contact Methods*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: location_contact_info.map_address_contact.primary.contact_methods[].method_type
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	method_type: prismic.SelectField<'phone' | 'email' | 'other'>;

	/**
	 * Value field in *LocationContactInfo → Map, Address & Contact → Primary → Contact Methods*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: location_contact_info.map_address_contact.primary.contact_methods[].value
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	value: prismic.KeyTextField;
}

/**
 * Primary content in *LocationContactInfo → Map, Address & Contact → Primary*
 */
export interface LocationContactInfoSliceMapAddressContactPrimary {
	/**
	 * Map Iframe field in *LocationContactInfo → Map, Address & Contact → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: location_contact_info.map_address_contact.primary.map_iframe
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	map_iframe: prismic.KeyTextField;

	/**
	 * Location Title field in *LocationContactInfo → Map, Address & Contact → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: location_contact_info.map_address_contact.primary.location_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	location_title: prismic.KeyTextField;

	/**
	 * Address field in *LocationContactInfo → Map, Address & Contact → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: location_contact_info.map_address_contact.primary.address
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	address: prismic.KeyTextField;

	/**
	 * Contact Title field in *LocationContactInfo → Map, Address & Contact → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: location_contact_info.map_address_contact.primary.contact_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	contact_title: prismic.KeyTextField;

	/**
	 * Contact Methods field in *LocationContactInfo → Map, Address & Contact → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: location_contact_info.map_address_contact.primary.contact_methods[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	contact_methods: prismic.GroupField<
		Simplify<LocationContactInfoSliceMapAddressContactPrimaryContactMethodsItem>
	>;
}

/**
 * Map, Address & Contact variation for LocationContactInfo Slice
 *
 * - **API ID**: `map_address_contact`
 * - **Description**: Standard layout with map on one side and location/contact details on the other.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LocationContactInfoSliceMapAddressContact = prismic.SharedSliceVariation<
	'map_address_contact',
	Simplify<LocationContactInfoSliceMapAddressContactPrimary>,
	never
>;

/**
 * Slice variation for *LocationContactInfo*
 */
type LocationContactInfoSliceVariation = LocationContactInfoSliceMapAddressContact;

/**
 * LocationContactInfo Shared Slice
 *
 * - **API ID**: `location_contact_info`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LocationContactInfoSlice = prismic.SharedSlice<
	'location_contact_info',
	LocationContactInfoSliceVariation
>;

/**
 * Primary content in *NewsletterSignup → Default → Primary*
 */
export interface NewsletterSignupSliceDefaultPrimary {
	/**
	 * Prompt Text field in *NewsletterSignup → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: newsletter_signup.default.primary.prompt_text
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	prompt_text: prismic.RichTextField;

	/**
	 * Placeholder Email field in *NewsletterSignup → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: newsletter_signup.default.primary.placeholder_email
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	placeholder_email: prismic.KeyTextField;

	/**
	 * Submit Action field in *NewsletterSignup → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: newsletter_signup.default.primary.submit_action
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	submit_action: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for NewsletterSignup Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard newsletter signup form with email input and submit button.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NewsletterSignupSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<NewsletterSignupSliceDefaultPrimary>,
	never
>;

/**
 * Primary content in *NewsletterSignup → NewsletterSignupXL → Primary*
 */
export interface NewsletterSignupSliceNewsletterSignupXlPrimary {
	/**
	 * Prompt Text field in *NewsletterSignup → NewsletterSignupXL → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: newsletter_signup.newsletterSignupXl.primary.prompt_text
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	prompt_text: prismic.RichTextField;

	/**
	 * Placeholder Email field in *NewsletterSignup → NewsletterSignupXL → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: newsletter_signup.newsletterSignupXl.primary.placeholder_email
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	placeholder_email: prismic.KeyTextField;

	/**
	 * Submit Action field in *NewsletterSignup → NewsletterSignupXL → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: newsletter_signup.newsletterSignupXl.primary.submit_action
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	submit_action: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * NewsletterSignupXL variation for NewsletterSignup Slice
 *
 * - **API ID**: `newsletterSignupXl`
 * - **Description**: Standard newsletter signup form with email input and submit button.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NewsletterSignupSliceNewsletterSignupXl = prismic.SharedSliceVariation<
	'newsletterSignupXl',
	Simplify<NewsletterSignupSliceNewsletterSignupXlPrimary>,
	never
>;

/**
 * Slice variation for *NewsletterSignup*
 */
type NewsletterSignupSliceVariation =
	| NewsletterSignupSliceDefault
	| NewsletterSignupSliceNewsletterSignupXl;

/**
 * NewsletterSignup Shared Slice
 *
 * - **API ID**: `newsletter_signup`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NewsletterSignupSlice = prismic.SharedSlice<
	'newsletter_signup',
	NewsletterSignupSliceVariation
>;

/**
 * Primary content in *Produits → Default → Primary*
 */
export interface ProduitsSliceDefaultPrimary {
	/**
	 * Image field in *Produits → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: produits.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Link field in *Produits → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: produits.default.primary.link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Label field in *Produits → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: produits.default.primary.label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;

	/**
	 * Image 2 field in *Produits → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: produits.default.primary.image_2
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image_2: prismic.ImageField<never>;

	/**
	 * Link 2 field in *Produits → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: produits.default.primary.link_2
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link_2: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Label 2 field in *Produits → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: produits.default.primary.label_2
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label_2: prismic.KeyTextField;

	/**
	 * Title field in *Produits → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: produits.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;

	/**
	 * Text field in *Produits → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: produits.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	text: prismic.RichTextField;
}

/**
 * Default variation for Produits Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProduitsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ProduitsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Produits*
 */
type ProduitsSliceVariation = ProduitsSliceDefault;

/**
 * Produits Shared Slice
 *
 * - **API ID**: `produits`
 * - **Description**: Produits
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProduitsSlice = prismic.SharedSlice<'produits', ProduitsSliceVariation>;

/**
 * Primary content in *Texte → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
	/**
	 * Content field in *Texte → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Lorem ipsum...
	 * - **API ID Path**: rich_text.default.primary.content
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content: prismic.RichTextField;
}

/**
 * Default variation for Texte Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<RichTextSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Texte*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * Texte Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSlice = prismic.SharedSlice<'rich_text', RichTextSliceVariation>;

/**
 * Primary content in *Espace → Espace → Primary*
 */
export interface SpacerSliceDefaultPrimary {
	/**
	 * Choix field in *Espace → Espace → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: Petit
	 * - **API ID Path**: spacer.default.primary.size
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	size: prismic.SelectField<'Petit' | 'Moyen' | 'Grand', 'filled'>;
}

/**
 * Espace variation for Espace Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SpacerSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<SpacerSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Espace*
 */
type SpacerSliceVariation = SpacerSliceDefault;

/**
 * Espace Shared Slice
 *
 * - **API ID**: `spacer`
 * - **Description**: Spacer
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SpacerSlice = prismic.SharedSlice<'spacer', SpacerSliceVariation>;

/**
 * Default variation for Title Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TitleSliceDefault = prismic.SharedSliceVariation<
	'default',
	Record<string, never>,
	never
>;

/**
 * Slice variation for *Title*
 */
type TitleSliceVariation = TitleSliceDefault;

/**
 * Title Shared Slice
 *
 * - **API ID**: `title`
 * - **Description**: Title
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TitleSlice = prismic.SharedSlice<'title', TitleSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	interface CreateWriteClient {
		(
			repositoryNameOrEndpoint: string,
			options: prismic.WriteClientConfig
		): prismic.WriteClient<AllDocumentTypes>;
	}

	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			AppellationDocument,
			AppellationDocumentData,
			CategoriesDocument,
			CategoriesDocumentData,
			CaveDocument,
			CaveDocumentData,
			CaveDocumentDataSlicesSlice,
			CouleurDocument,
			CouleurDocumentData,
			DomaineDocument,
			DomaineDocumentData,
			EpicerieDocument,
			EpicerieDocumentData,
			EpicerieDocumentDataSlicesSlice,
			OrigineDocument,
			OrigineDocumentData,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			RegionDocument,
			RegionDocumentData,
			SettingsDocument,
			SettingsDocumentData,
			SettingsDocumentDataNavigationItem,
			SettingsDocumentDataItemItem,
			SettingsDocumentDataSlices3Slice,
			SettingsDocumentDataSlices4Slice,
			VinDocument,
			VinDocumentData,
			VinDocumentDataSlicesSlice,
			AllDocumentTypes,
			BannerEventSlice,
			BannerEventSliceDefaultPrimary,
			BannerEventSliceBannerEventXlPrimary,
			BannerEventSliceVariation,
			BannerEventSliceDefault,
			BannerEventSliceBannerEventXl,
			BannerReviewSlice,
			BannerReviewSliceDefaultPrimary,
			BannerReviewSliceDefaultItem,
			BannerReviewSliceVariation,
			BannerReviewSliceDefault,
			BannerSocialSlice,
			BannerSocialSliceDefaultPrimary,
			BannerSocialSliceDefaultItem,
			BannerSocialSliceVariation,
			BannerSocialSliceDefault,
			GalleryGridSlice,
			GalleryGridSliceThreeByTwoGridPrimaryImagesItem,
			GalleryGridSliceThreeByTwoGridPrimary,
			GalleryGridSliceVariation,
			GalleryGridSliceThreeByTwoGrid,
			HeroSlice,
			HeroSliceDefaultPrimary,
			HeroSliceHeroTextOnlyPrimary,
			HeroSliceVariation,
			HeroSliceDefault,
			HeroSliceHeroTextOnly,
			LocationContactInfoSlice,
			LocationContactInfoSliceMapAddressContactPrimaryContactMethodsItem,
			LocationContactInfoSliceMapAddressContactPrimary,
			LocationContactInfoSliceVariation,
			LocationContactInfoSliceMapAddressContact,
			NewsletterSignupSlice,
			NewsletterSignupSliceDefaultPrimary,
			NewsletterSignupSliceNewsletterSignupXlPrimary,
			NewsletterSignupSliceVariation,
			NewsletterSignupSliceDefault,
			NewsletterSignupSliceNewsletterSignupXl,
			ProduitsSlice,
			ProduitsSliceDefaultPrimary,
			ProduitsSliceVariation,
			ProduitsSliceDefault,
			RichTextSlice,
			RichTextSliceDefaultPrimary,
			RichTextSliceVariation,
			RichTextSliceDefault,
			SpacerSlice,
			SpacerSliceDefaultPrimary,
			SpacerSliceVariation,
			SpacerSliceDefault,
			TitleSlice,
			TitleSliceVariation,
			TitleSliceDefault
		};
	}
}
